version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: c_backend
    ports:
      - '8000:8000'
    volumes:
      # Bind mount volume for live backend updates while developing
      - ./backend:/backend

  frontend:
    build: ./frontend
    container_name: c_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/client/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
